In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import kagglehub
path = kagglehub.dataset_download("satyakidas07/retail-sales-dataset")
import os
import glob
# The 'path' variable from the previous cell contains the directory where the dataset was downloaded.
# It is '/root/.cache/kagglehub/datasets/satyakidas07/retail-sales-dataset/versions/1'
# We need to find the actual CSV file within this directory.

csv_files = glob.glob(os.path.join(path, '*.csv'))

if csv_files:
    data_file_path = csv_files[0]
    df = pd.read_csv(data_file_path)
    print(f"Successfully loaded data from: {data_file_path}")
else:
    raise FileNotFoundError(f"No CSV files found in the dataset directory: {path}")

Using Colab cache for faster access to the 'retail-sales-dataset' dataset.
Successfully loaded data from: /kaggle/input/retail-sales-dataset/retail_sales_dataset.csv

In [7]:
df

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
0,ORD-03903,2024-08-15,CUST32603,Aarav Mehta,39.0,Other,Central,Raipur,Groceries,Sugar,...,346.32,NaN,4043.14,289.18,56.04,Debit Card,NaN,True,Returned,7.0
1,ORD-02198,2022-08-16,CUST07881,Sanjay Verma,28.0,Male,West,Mumbai,Beauty,Sunscreen,...,858.66,0.08,9147.31,5355.56,64.49,Debit Card,5.0,False,Delivered,2.0
2,ORD-01348,2021-08-29,CUST49296,Pooja Sharma,41.0,Other,West,Surat,Furniture,Sofa,...,25941.32,0.14,110156.97,36956.51,67.65,Debit Card,4.0,False,Delivered,5.0
3,ORD-02076,2022-07-05,CUST05587,Priya Reddy,29.0,Other,West,Ahmedabad,Furniture,Bed Frame,...,22071.92,0.17,262066.11,66644.99,54.47,EMI,3.0,False,Delivered,4.0
4,ORD-00287,2020-05-07,CUST58035,Ritu Sharma,9.0,Male,Central,Nagpur,Groceries,Cooking Oil,...,320.06,0.31,323.95,31.38,48.81,Net Banking,4.0,False,Pending,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4305,ORD-00056,2020-01-21,CUST85136,Sanjay Sharma,45.0,F,West,Pune,Sports,Football,...,1871.46,0.22,6895.34,1811.03,62.59,EMI,NaN,True,Returned,9.0
4306,ORD-03458,2024-02-08,CUST09746,Karan Pillai,25.0,m,South,Chennai,Clothing,Kurta,...,3147.97,0.13,22125.94,10153.44,38.76,EMI,2.0,False,Cancelled,2.0
4307,ORD-01769,2022-02-22,CUST64190,Karan Reddy,39.0,Male,East,Guwahati,Beauty,Face Cream,...,422.45,0.02,2726.49,759.36,39.41,Credit Card,NaN,False,Delivered,5.0
4308,ORD-01738,2022-02-11,CUST50460,Amit Mehta,40.0,Female,East,Bhubaneswar,Books,Biography,...,1456.57,0.27,4835.66,2312.44,71.90,Cash on Delivery,1.0,False,Cancelled,4.0
4309,ORD-03241,2023-11-01,CUST36164,Nikhil Rao,23.0,Other,North,Delhi,Furniture,Desk,...,28349.81,0.14,211857.48,59966.21,53.88,Debit Card,2.0,False,Delivered,2.0

In [8]:
# Get the data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4310 entries, 0 to 4309
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               4280 non-null   object
 1   order_date             4280 non-null   object
 2   customer_id            4280 non-null   object
 3   customer_name          4280 non-null   object
 4   age                    4150 non-null   float64
 5   gender                 4280 non-null   object
 6   region                 4280 non-null   object
 7   city                   4280 non-null   object
 8   product_category       4280 non-null   object
 9   product_name           4280 non-null   object
 10  quantity               4170 non-null   float64
 11  unit_price             4280 non-null   float64
 12  discount_pct           4143 non-null   float64
 13  sales_amount           4280 non-null   float64
 14  profit                 4280 non-null   float64
 15  shipping_cost          4280 non-null   float64
 16  payment_method         4280 non-null   object
 17  customer_satisfaction  3932 non-null   float64
 18  return_flag            4280 non-null   object
 19  order_status           4280 non-null   object
 20  days_to_ship           4180 non-null   float64
dtypes: float64(9), object(12)
memory usage: 707.2+ KB

In [10]:
df.describe().round()

,age,quantity,unit_price,discount_pct,sales_amount,profit,shipping_cost,customer_satisfaction,days_to_ship
count,4150.0,4170.0,4280.0,4143.0,4280.0,4280.0,4280.0,3932.0,4180.0
mean,35.0,7.0,10621.0,0.0,62359.0,11687.0,63.0,3.0,6.0
std,36.0,44.0,17324.0,0.0,316700.0,52875.0,18.0,1.0,4.0
min,-7.0,-1.0,50.0,0.0,39.0,2.0,-4.0,1.0,-1.0
25%,26.0,3.0,672.0,0.0,2462.0,702.0,51.0,2.0,3.0
50%,34.0,5.0,2228.0,0.0,9548.0,3128.0,63.0,3.0,6.0
75%,42.0,8.0,12717.0,0.0,50070.0,10404.0,76.0,4.0,8.0
max,999.0,999.0,79958.0,0.0,17360314.0,2445648.0,133.0,5.0,100.0

In [14]:
# Count of missing values
df.isnull().sum()

order_id                  30
order_date                30
customer_id               30
customer_name             30
age                      160
gender                    30
region                    30
city                      30
product_category          30
product_name              30
quantity                 140
unit_price                30
discount_pct             167
sales_amount              30
profit                    30
shipping_cost             30
payment_method            30
customer_satisfaction    378
return_flag               30
order_status              30
days_to_ship             130
dtype: int64

In [15]:
df.shape

(4310, 21)

In [19]:
# Percentage of the missing datavalues
(df.isnull().sum()/len(df)*100)

order_id                 0.696056
order_date               0.696056
customer_id              0.696056
customer_name            0.696056
age                      3.712297
gender                   0.696056
region                   0.696056
city                     0.696056
product_category         0.696056
product_name             0.696056
quantity                 3.248260
unit_price               0.696056
discount_pct             3.874710
sales_amount             0.696056
profit                   0.696056
shipping_cost            0.696056
payment_method           0.696056
customer_satisfaction    8.770302
return_flag              0.696056
order_status             0.696056
days_to_ship             3.016241
dtype: float64

In [23]:
df[df.duplicated()].shape

(109, 21)

In [18]:
# ERRORS IN DATASET
# age min negative
# quantity min negative
# shipping cost is min negative
# days to ship m min is also negative here.